INSERT INTO ARTICULO VALUES (1, 20, 'ZAPALLO', 500);
INSERT INTO ARTICULO VALUES (2, 10, 'PAPA', 700);
INSERT INTO ARTICULO VALUES (3, 60, 'PALTA', 2000);

INSERT INTO SUCURSAL VALUES (1, 'Lujan');
INSERT INTO SUCURSAL VALUES (2, 'Palermo');
INSERT INTO SUCURSAL VALUES (3, 'Rosario');

INSERT INTO VENDE VALUES (1, 1, 200, 10);
INSERT INTO VENDE VALUES (1, 2, 200, 10);
INSERT INTO VENDE VALUES (2, 1, 200, 10);
INSERT INTO VENDE VALUES (3, 1, 200, 10);

SELECT *
FROM VENDE V
WHERE V.ID_SUC NOT IN (
  SELECT G.ID_SUC
  FROM VENDE G
  WHERE G.ID_SUC = 2
)
AND 
V.ID_SUC = 1