INSERT INTO INGREDIENTE (ID_ING, NOMBRE) VALUES(2, 'DULCE DE LECHE');
INSERT INTO INGREDIENTE (ID_ING, NOMBRE) VALUES(1, 'HARINA');
INSERT INTO INGREDIENTE (ID_ING, NOMBRE) VALUES(3, 'CREMA');
INSERT INTO INGREDIENTE (ID_ING, NOMBRE) VALUES(4, 'MANTECA');


INSERT INTO PROVEEDOR VALUES(3, 'BIMBO');
INSERT INTO PROVEEDOR VALUES(2, 'SANCOR');
INSERT INTO PROVEEDOR VALUES(1, 'SERENISIMA');

INSERT INTO COMPRA VALUES(1, 2, CURRENT_DATE - 7, 20000, 40000);
INSERT INTO COMPRA VALUES(3, 2, CURRENT_DATE - 10, 20000, 40000);
INSERT INTO COMPRA VALUES(3, 1, CURRENT_DATE - 10, 20000, 40000);
INSERT INTO COMPRA VALUES(3, 1, CURRENT_DATE - 11, 20000, 40000);

SELECT MAX(SUMATORIA), SUB.CUIT_P
FROM (
  SELECT SUM(C.CANTIDAD) AS SUMATORIA, C.CUIT_P
  FROM COMPRA C
  GROUP BY C.CUIT_P
) AS SUB
GROUP BY SUB.CUIT_P
;
