CREATE TABLE EQUIPO (
    ID_E DOM_NRO,
    CONSTRAINT PK_EQUIPO PRIMARY KEY (ID_E)
);

CREATE TABLE AUTORIDAD (
    ID_A DOM_NRO,
    NOMBRE DOM_DESCRIPCION,
    APELLIDO DOM_DESCRIPCION
    CONSTRAINT PK_AUTORIDAD PRIMARY KEY (ID_A)
);

CREATE TABLE LUGAR (
    ESTADIO DOM_DESCRIPCION,
    CONSTRAINT PK_LUGAR PRIMARY KEY (ESTADIO);
);

CREATE TABLE PARTIDO (
    ID_P DOM_NRO,
    FECHA DATE DEFAULT CURRENT_DATE NOT NULL,
    HORA_DESDE TIME NOT NULL,
    HORA_HASTA TIME NOT NULL,
    GOLES_LOCAL INTEGER,
    GOLES_VISITANTE INTEGER,
    RESULTADO VARCHAR(10) CHECK(RESULTADO = 'visitante' OR RESULTADO = 'local' OR RESULTADO = 'empate'),
    JL1 DOM_NRO,
    JL2 DOM_NRO,
    AR DOM_NRO,
    ESTADIO DOM_DESCRIPCION,
    VISITANTE DOM_NRO,
    LOCALE DOM_NRO
    CONSTRAINT PK_PARTIDO PRIMARY KEY (ID_P),
    CONSTRAINT FK_PARTIDO_JL1 FOREIGN KEY (JL1) REFERENCES AUTORIDAD(ID_A), 
    CONSTRAINT FK_PARTIDO_JL2 FOREIGN KEY (JL2) REFERENCES AUTORIDAD(ID_A), 
    CONSTRAINT FK_PARTIDO_AR FOREIGN KEY (AR) REFERENCES AUTORIDAD(ID_A),
    CONSTRAINT FK_PARTIDO_LUGAR FOREIGN KEY (ESTADIO) REFERENCES LUGAR(ESTADIO),
    CONSTRAINT FK_PARTIDO_VISITANTE FOREIGN KEY (VISITANTE) REFERENCES EQUIPO(ID_E),
    CONSTRAINT FK_PARTIDO_LOCALE FOREIGN KEY (LOCALE) REFERENCES EQUIPO(ID_E)
)

