CREATE TABLE GUIA (
    DNI DOM_NRO,
    NOMBRE DOM_DESCRIPCION,
    APELLIDO DOM_DESCRIPCION,
    MAIL DOM_DESCRIPCION,
    TE DOM_DESCRIPCION,
    CONSTRAINT PK_GUIA PRIMARY KEY (DNI)
);

CREATE TABLE CLIENTE (
    IDC DOM_NRO,
    NOMBRE DOM_DESCRIPCION,
    APELLIDO DOM_DESCRIPCION,
    MAIL DOM_DESCRIPCION,
    DIRECCION DOM_DESCRIPCION,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (IDC)
);

CREATE TABLE TOUR (
    IDT DOM_NRO,
    DESCRIPCION DOM_DESCRIPCION,
    OBSERVACIONES VARCHAR(200),
    CONSTRAINT PK_TOUR PRIMARY KEY (IDT)
);

CREATE TABLE VIAJE (
    IDV DOM_NRO,
    FECHA DATE DEFAULT CURRENT_DATE NOT NULL,
    PRECIO DOUBLE PRECISION DEFAULT 0 NOT NULL,
    DNI DOM_NRO,
    IDT DOM_NRO,
    CONSTRAINT PK_VIAJE PRIMARY KEY (IDV),
    CONSTRAINT FK_VIAJE_GUIA FOREIGN KEY (DNI) REFERENCES GUIA(DNI),
    CONSTRAINT FK_VIAJE_TOUR FOREIGN KEY (IDT) REFERENCES TOUR(IDT)
);

CREATE TABLE CONTRATADO (
    IDV DOM_NRO,
    IDC DOM_NRO,
    CANTCUOTAS DOM_NRO,
    CONSTRAINT PK_CONTRATADO PRIMARY KEY (IDV, IDC),
    CONSTRAINT FK_CONTRATADO_VIAJE FOREIGN KEY (IDV) REFERENCES VIAJE(IDV),
    CONSTRAINT FK_CONTRATADO_CLIENTE FOREIGN KEY (IDC) REFERENCES CLIENTE(IDC)
);