CREATE TABLE ANALISTA
(
  DNI DOM_NRO NOT NULL,
  CONSTRAINT PK_ANALISTA PRIMARY KEY (DNI),
  CONSTRAINT FK_ANALISTA_EMPLEADO FOREIGN KEY (DNI) REFERENCES EMPLEADO(DNI)
);

CREATE TABLE LENGUAJE
(
  ID_LENGUAJE DOM_NRO NOT NULL,
  NOMBRE VARCHAR(20) NOT NULL,
  CONSTRAINT PK_LENGUAJE PRIMARY KEY (ID_LENGUAJE)
);

CREATE TABLE GERENCIA
(
  ID_GERENCIA DOM_NRO NOT NULL,
  NOMBRE DOM_DESCRIPCION,
  CONSTRAINT PK_GERENCIA PRIMARY KEY (ID_GERENCIA)
);

CREATE TABLE EMPLEADO
(
  DNI integer NOT NULL,
  NOMBRE DOM_DESCRIPCION,
  APELLIDO DOM_DESCRIPCION,
  CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI)
);

CREATE TABLE PROGRAMADOR
(
  DNI DOM_NUM NOT NULL,
  CONSTRAINT PK_PROGRAMADOR PRIMARY KEY (DNI),
  CONSTRAINT FK_PROGRAMADOR_EMPLEADO FOREIGN KEY (DNI) REFERENCES EMPLEADO(DNI)
);

CREATE TABLE PROYECTO
(
  ID_PROYECTO DOM_NUM NOT NULL,
  NOMBRE DOM_DESCRIPCION,
  PRESUPUESTO double precision DEFAULT 0 NOT NULL,
  ID_GERENCIA DOM_NUM,
  CONSTRAINT PK_PROYECTO PRIMARY KEY (ID_PROYECTO),
  CONSTRAINT FK_PROYECTO_GERENCIA FOREIGN KEY (ID_GERENCIA) REFERENCES GERENCIA(ID_GERENCIA)
);

CREATE TABLE CONOCE
(
  DNI DOM_NUM NOT NULL,
  ID_LENGUAJE DOM_NUM NOT NULL,
  NIVEL integer DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CONOCE PRIMARY KEY (DNI,ID_LENGUAJE),
  CONSTRAINT FK_CONOCE_DNI FOREIGN KEY (DNI) REFERENCES PROGRAMADOR(DNI)
);

CREATE TABLE TRABAJA
(
  DNI integer NOT NULL,
  ID_PROYECTO DOM_NUM NOT NULL,
  HORAS_SEMANALES DOM_NUM,
  CONSTRAINT PK_TRABAJA PRIMARY KEY (DNI,ID_PROYECTO),
  CONSTRAINT FK_TRABAJA_EMPLEADO FOREIGN KEY (DNI) REFERENCES EMPLEADO(DNI),
  CONSTRAINT FK_TRABAJA_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO(ID_PROYECTO)
);