CREATE TABLE MEDICO (
    MATRICULA DOM_NRO,
    NOMBRE DOM_DESCRIPCION,
    APELLIDO DOM_DESCRIPCION,
    CONSTRAINT PK_MEDICO PRIMARY KEY (MATRICULA)
);

CREATE TABLE PACIENTE (
    DNI DOM_NRO,
    NOMBRE DOM_DESCRIPCION,
    APELLIDO DOM_DESCRIPCION,
    CONSTRAINT PK_PACIENTE PRIMARY KEY (DNI)
);

CREATE TABLE OBRASOCIAL (
    ID_O DOM_NRO,
    NOMBRE DOM_DESCRIPCION,
    CONSTRAINT PK_OBRASOCIAL PRIMARY KEY (ID_O)
);

CREATE TABLE PRACTICA (
    ID_P DOM_NRO,
    DESCRIPCION DOM_DESCRIPCION,
    PRECIO DOUBLE PRECISION DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PRACTICA PRIMARY KEY (ID_P)
);

CREATE TABLE CONSULTA (
    ID_C DOM_NRO,
    INDICACIONES DOM_DESCRIPCION,
    DIAGNOSTICO DOM_DESCRIPCION,
    FECHA DATE DEFAULT CURRENT_DATE NOT NULL,
    IMPORTE DOUBLE PRECISION DEFAULT 0 NOT NULL,
    DNI DOM_NRO,
    MATRICULA DOM_NRO,
    ID_O DOM_NRO,
    CONSTRAINT PK_CONSULTA PRIMARY KEY (ID_C),
    CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (DNI) REFERENCES PACIENTE(DNI),
    CONSTRAINT FK_CONSULTA_MEDICO FOREIGN KEY (MATRICULA) REFERENCES MEDICO(MATRICULA),
    CONSTRAINT FK_CONSULTA_OBRASOCIAL FOREIGN KEY (ID_O) REFERENCES OBRASOCIAL(ID_O)
);

CREATE TABLE SOLICITA (
    ID_C DOM_NRO,
    ID_P DOM_NRO,
    PRECIO DOUBLE PRECISION,
    RESULTADO VARCHAR(100),
    IMPORTE DOUBLE PRECISION DEFAULT 0 NOT NULL,
    ID_O DOM_NRO,
    CONSTRAINT PK_SOLICITA PRIMARY KEY (ID_C),
    CONSTRAINT FK_SOLICITA_CONSULTA FOREIGN KEY (ID_C) REFERENCES CONSULTA(ID_C),
    CONSTRAINT FK_SOLICITA_PRACTICA FOREIGN KEY (ID_P) REFERENCES PRACTICA(ID_P),
    CONSTRAINT FK_SOLICITA_OBRASOCIAL FOREIGN KEY (ID_O) REFERENCES OBRASOCIAL(ID_O)
);