CREATE TABLE ALUMNO
(
  LEGAJO integer NOT NULL,
  DNI integer NOT NULL,
  NOMBRE VARCHAR(100),
  ID_C INTEGER,
  CONSTRAINT PK_ALUMNO PRIMARY KEY (LEGAJO),
  CONSTRAINT UNIQUE_ALUMNO_DNI UNIQUE (DNI)
);

CREATE TABLE AUTOR
(
  ID_A INTEGER NOT NULL,
  NOMBRE VARCHAR(100),
  CONSTRAINT PK_AUTOR PRIMARY KEY (ID_A)
);

CREATE TABLE CARRERA
(
  ID_C INTEGER NOT NULL,
  NOMBRE VARCHAR(100),
  CONSTRAINT PK_CARRERA PRIMARY KEY (ID_C)
);

CREATE TABLE EDITORIAL
(
  ID_ED INTEGER NOT NULL,
  NOMBRE VARCHAR(100),
  CONSTRAINT PK_EDITORIAL PRIMARY KEY (ID_ED)
);

CREATE TABLE LIBRO
(
  ISBN integer NOT NULL,
  NOMBRE VARCHAR(100),
  CANT_EJEMPLARES integer DEFAULT 0 NOT NULL,
  ID_ED INTEGER,
  CONSTRAINT PK_LIBRO PRIMARY KEY (ISBN),
  CONSTRAINT FK_LIBRO_EDITORIAL FOREIGN KEY (ID_ED) REFERENCES EDITORIAL(ID_ED)
);

CREATE TABLE TEMA
(
  ID_T INTEGER NOT NULL,
  NOMBRE VARCHAR(100),
  CONSTRAINT PK_TEMA PRIMARY KEY (ID_T)
);

CREATE TABLE CONTIENE
(
  ID_T INTEGER NOT NULL,
  ISBN integer NOT NULL,
  CONSTRAINT PK_CONTIENE PRIMARY KEY (ID_T,ISBN),
  CONSTRAINT FK_CONTIENE_TEMA FOREIGN KEY (ID_T) REFERENCES TEMA(ID_T),
  CONSTRAINT FK_CONTIENE_LIBRO FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN)
);

CREATE TABLE EJEMPLAR
(
  ID_EJ INTEGER NOT NULL,
  PRESTADO boolean DEFAULT FALSE NOT NULL,
  ISBN integer NOT NULL,
  CONSTRAINT PK_EJEMPLAR PRIMARY KEY (ID_EJ,ISBN),
  CONSTRAINT FK_EJEMPLAR_LIBRO FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN)
);

CREATE TABLE ESCRIBIO
(
  ID_A INTEGER NOT NULL,
  ISBN integer NOT NULL,
  CONSTRAINT PK_ESCRIBIO PRIMARY KEY (ID_A,ISBN),
  CONSTRAINT FK_ESCRIBIO_AUTOR FOREIGN KEY (ID_A) REFERENCES AUTOR(ID_A),
  CONSTRAINT FK_ESCRIBIO_LIBRO FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN)
);

CREATE TABLE PRESTO
(
  LEGAJO integer NOT NULL,
  ISBN integer NOT NULL,
  ID_EJ INTEGER NOT NULL,
  FECHA_INICIO date DEFAULT CURRENT_DATE NOT NULL,
  FECHA_DEVOLUCION date,
  FECHA_LIMITE date NOT NULL,
  CONSTRAINT PK_PRESTO PRIMARY KEY (LEGAJO,ISBN,ID_EJ),
  CONSTRAINT FK_PRESTO_EJEMPLAR FOREIGN KEY (ID_EJ, ISBN) REFERENCES EJEMPLAR(ID_EJ, ISBN)
);