CREATE TABLE CLIENTE
(
  CUIT integer NOT NULL,
  RAZON DOM_DESCRIPCION,
  SALDO double precision DEFAULT 0 NOT NULL,
  CONSTRAINT PK_CLIENTE PRIMARY KEY (CUIT)
);

CREATE TABLE ESPECIALISTA
(
  ID_E DOM_NRO NOT NULL,
  NOMBRE DOM_DESCRIPCION,
  CONSTRAINT PK_ESPECIALISTA PRIMARY KEY (ID_E)
);

CREATE TABLE PRODUCTO
(
  ID_P DOM_NRO NOT NULL,
  ID_E DOM_NRO NOT NULL,
  NOMBRE DOM_DESCRIPCION,
  PRECIO double precision DEFAULT 0 NOT NULL,
  STOCK DOM_NRO,
  CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_P),
  CONSTRAINT FK_PRODUCTO_ESPECIALISTA FOREIGN KEY (ID_P) REFERENCES ESPECIALISTA(ID_E)
);

CREATE TABLE INGREDIENTE
(
  ID_ING DOM_NRO NOT NULL,
  NOMBRE DOM_DESCRIPCION,
  FECHA_ULTIMO_PRECIO date,
  ULTIMO_PRECIO double precision,
  CONSTRAINT PK_INGREDIENTE PRIMARY KEY (ID_ING)
);

CREATE TABLE PROVEEDOR
(
  CUIT_P integer NOT NULL,
  RAZON DOM_DESCRIPCION,
  CONSTRAINT PK_PROVEEDOR PRIMARY KEY (CUIT_P)
);

CREATE TABLE USA
(
  ID_P DOM_NRO NOT NULL,
  ID_ING DOM_NRO NOT NULL,
  CANTIDAD DOM_NRO DEFAULT 0 NOT NULL,
  CONSTRAINT PK_USA PRIMARY KEY (ID_P, ID_ING),
  CONSTRAINT FK_USA_PRODUCTO FOREIGN KEY (ID_P) REFERENCES PRODUCTO(ID_P),
  CONSTRAINT FK_USA_INGREDIENTE FOREIGN KEY (ID_ING) REFERENCES INGREDIENTE(ID_ING)
);

CREATE TABLE COMPRA
(
  ID_ING DOM_NRO NOT NULL,
  CUIT_P integer NOT NULL,
  FECHA date DEFAULT CURRENT_DATE NOT NULL,
  PRECIO double precision DEFAULT 0 NOT NULL,
  CANTIDAD DOM_NRO,
  CONSTRAINT PK_COMPRA PRIMARY KEY (ID_ING,CUIT_P,FECHA),
  CONSTRAINT FK_COMPRA_PROVEEDOR FOREIGN KEY (CUIT_P) REFERENCES PROVEEDOR(CUIT_P),
  CONSTRAINT FK_COMPRA_INGREDIENTE FOREIGN KEY (ID_ING) REFERENCES INGREDIENTE(ID_ING)
);

CREATE TABLE FACTURA
(
  NRO_F DOM_NRO NOT NULL,
  FECHA_EMISION date DEFAULT CURRENT_DATE NOT NULL,
  FECHA_LIMITE date NOT NULL,
  PAGO boolean DEFAULT FALSE NOT NULL,
  MONTO double precision DEFAULT 0 NOT NULL,
  CUIT integer NOT NULL,
  CONSTRAINT PK_FACTURA PRIMARY KEY (NRO_F),
  CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (CUIT) REFERENCES CLIENTE(CUIT)
);

CREATE TABLE FACTURAR
(
  NRO_F DOM_NRO NOT NULL,
  ID_P DOM_NRO NOT NULL,
  PRECIO double precision DEFAULT 0 NOT NULL,
  CANTIDAD DOM_NRO,
  CONSTRAINT PK_FACTURAR PRIMARY KEY (NRO_F,ID_P),
  CONSTRAINT FK_FACTURAR_PRODUCTO FOREIGN KEY (ID_P) REFERENCES PRODUCTO(ID_P)
);